code = """const RELAY_SECRET = PropertiesService.getScriptProperties().getProperty('RELAY_SECRET');
const ADMIN_EMAILS = "asha.suhasinim@gmail.com,ymvshiva1784@gmail.com";

function doGet(e) {
  return ContentService.createTextOutput(JSON.stringify({
    success: true,
    message: "Asha Mental Wellness Review Email Relay is active."
  })).setMimeType(ContentService.MimeType.JSON);
}

function doPost(e) {
  try {
    if (!RELAY_SECRET) {
      return ContentService.createTextOutput(JSON.stringify({ success: false, error: "Relay not configured" })).setMimeType(ContentService.MimeType.JSON);
    }
    
    var postData = JSON.parse(e.postData.contents);
    var providedSecret = postData.secret;
    
    if (providedSecret !== RELAY_SECRET) {
      return ContentService.createTextOutput(JSON.stringify({ success: false, error: "Unauthorized" })).setMimeType(ContentService.MimeType.JSON);
    }
    
    var subject = postData.subject;
    var htmlBody = postData.htmlBody;
    var recipient = postData.to || ADMIN_EMAILS;
    
    var calendarEventId = postData.calendarEventId || null;
    var meetingUrl = postData.meetingUrl || null;
    var calendarError = null;

    if (postData.createCalendarEvent && !calendarEventId) {
      try {
        var evt = postData.createCalendarEvent;
        // Use the deterministic booking ID for true idempotency
        var reqId = evt.bookingId ? "meet_" + evt.bookingId : Math.random().toString(36).substring(7);
        
        var event = {
          summary: evt.title,
          location: 'Online Session',
          description: 'Mental Wellness Session',
          start: { dateTime: evt.startTime, timeZone: 'Asia/Kolkata' },
          end: { dateTime: evt.endTime, timeZone: 'Asia/Kolkata' },
          attendees: [{email: evt.guestEmail}],
          conferenceData: {
            createRequest: {
              requestId: reqId,
              conferenceSolutionKey: { type: "hangoutsMeet" }
            }
          }
        };
        
        // Requires Advanced Calendar Service to be enabled in Apps Script editor
        var createdEvent = Calendar.Events.insert(event, 'primary', {
          conferenceDataVersion: 1,
          sendUpdates: 'all'
        });
        
        calendarEventId = createdEvent.id;
        if (createdEvent.conferenceData && createdEvent.conferenceData.entryPoints && createdEvent.conferenceData.entryPoints.length > 0) {
            // Find the video entry point specifically
            var videoEntry = createdEvent.conferenceData.entryPoints.filter(function(ep) { return ep.entryPointType === 'video'; })[0];
            meetingUrl = videoEntry ? videoEntry.uri : createdEvent.conferenceData.entryPoints[0].uri;
        } else {
            meetingUrl = createdEvent.hangoutLink;
        }
        
        if (!meetingUrl) {
            throw new Error("Calendar event created but no Meet URL was generated by Google.");
        }
      } catch (calError) {
        calendarError = calError.toString();
        console.error("Calendar creation failed: " + calendarError);
        // CRITICAL: Abort immediately if Calendar creation fails for an approval
        return ContentService.createTextOutput(JSON.stringify({
            success: false,
            error: "Calendar/Meet creation failed",
            calendarError: calendarError
        })).setMimeType(ContentService.MimeType.JSON);
      }
    }

    if (postData.replaceMeetPlaceholder) {
        if (!meetingUrl) {
             return ContentService.createTextOutput(JSON.stringify({
                success: false,
                error: "Missing Meet URL for customer confirmation email",
                calendarEventId: calendarEventId
            })).setMimeType(ContentService.MimeType.JSON);
        }
        htmlBody = htmlBody.replace("{{MEET_URL}}", meetingUrl);
    }

    var emailSent = false;
    var emailError = null;
    if (subject && htmlBody) {
      try {
        MailApp.sendEmail({
          to: recipient,
          subject: subject,
          htmlBody: htmlBody
        });
        emailSent = true;
      } catch(err) {
        emailError = err.toString();
        // CRITICAL: Abort if Email fails
        return ContentService.createTextOutput(JSON.stringify({
            success: false,
            error: "Email sending failed",
            emailError: emailError,
            calendarEventId: calendarEventId,
            meetingUrl: meetingUrl
        })).setMimeType(ContentService.MimeType.JSON);
      }
    }
    
    return ContentService.createTextOutput(JSON.stringify({ 
        success: true, 
        message: "Operation completed successfully",
        calendarEventId: calendarEventId,
        meetingUrl: meetingUrl,
        emailSent: true
    })).setMimeType(ContentService.MimeType.JSON);
      
  } catch (error) {
    return ContentService.createTextOutput(JSON.stringify({ success: false, error: error.toString() })).setMimeType(ContentService.MimeType.JSON);
  }
}
"""

with open("google_apps_script/Code.gs", "w", encoding="utf-8") as f:
    f.write(code)

print("Updated google_apps_script/Code.gs")
